#!/usr/bin/env python
import csv, os, sys, textwrap
import xml.etree.ElementTree as ElementTree

if __name__ == "__main__":
    if len(sys.argv) < 2:
        help_msg = 'This program takes a directory that contains one or more csv files as input and creates a sequence of .dc.xml files in that directory as output. The name of each CSV file that is outputted is constructed from the identifier in the CSV file itself.'
        
        for line in textwrap.wrap(help_msg):
            sys.stdout.write('{}\n'.format(line))
        sys.stdout.write('\nUsage:\n')
        sys.stdout.write(' python csv2dc.py a_directory_containing_csv_files\n')
        sys.exit()

    for filename in os.listdir(sys.argv[1]):
        # only process .csv files.
        if filename[-4:] != '.csv':
            continue
        with open('{}{}{}'.format(sys.argv[1], os.sep, filename)) as c:
            reader = csv.reader(c)
            for row in reader:
                if row[0] == 'Title':
                    continue
                identifier = row[2]
                metadata = ElementTree.fromstring('<metadata></metadata>')
                ElementTree.SubElement(metadata, 'title').text = row[0]
                ElementTree.SubElement(metadata, 'date').text = row[1]
                ElementTree.SubElement(metadata, 'description').text = row[3]
                ElementTree.SubElement(metadata, 'identifier').text = identifier
                ElementTree.ElementTree(metadata).write(
                    '{}{}{}.dc.xml'.format(sys.argv[1], os.sep, identifier),
                    encoding='utf-8',
                    xml_declaration=True
                )
