#!/usr/bin/env python
"""Usage:
    marc2dc [--socscimaps]
"""


import sys
from docopt import docopt
from classes import MarcToDc, SocSciMapsMarcToDc


def main():
        options = docopt(__doc__)

        if options['--socscimaps']:
            cls = SocSciMapsMarcToDc
        else:
            cls = MarcToDc
        sys.stdout.write(str(cls(sys.stdin.read())))


if __name__ == "__main__":
    main()
