#!/usr/bin/env python
"""Usage:
    marc2dc [--socscimaps]
"""

import sys
import xml.etree.ElementTree as ElementTree
from docopt import docopt
from classes import SocSciMapsMarcXmlToDc

ElementTree.register_namespace('m', 'http://www.loc.gov/MARC21/slim')

if __name__ == "__main__":
    options = docopt(__doc__)
    if options['--socscimaps']:
        records = ElementTree.fromstring(
            sys.stdin.read()
        ).findall('{http://www.loc.gov/MARC21/slim}record')

        if len(records) == 1:
            sys.stdout.write(
                str(
                    SocSciMapsMarcXmlToDc(
                        '<collection>{}</collection>'.format(
                            ElementTree.tostring(records[0], 'utf-8', method='xml').decode('utf-8')
                        )
                    )
                )
            )
        elif len(records) > 1:
            metadata = ElementTree.Element('metadata')
            for record in records:
                metadata.append(
                    SocSciMapsMarcXmlToDc(
                        '<collection>{}</collection>'.format(
                            ElementTree.tostring(record, 'utf-8', method='xml').decode('utf-8')
                        )
                    )._asxml()
                )
            sys.stdout.write(ElementTree.tostring(metadata, 'utf-8', method='xml').decode('utf-8'))
    else:
        raise NotImplementedError
