#!/usr/bin/env python
"""This script currently works for the Social Scientists Maps collection. """

import sys
from classes import SocSciMapsMarcXmlToEDM

if __name__ == "__main__":
    sys.stdout.write(str(SocSciMapsMarcXmlToEDM(sys.stdin.read())))
