#!/usr/bin/env python
"""Usage:
    marc2dc -
    marc2dc -f <path>
Options:
  -h --help     Show this screen.
  -f --file     File path to make manifest from
  -             Take input from the terminal
"""


import sys
from docopt import docopt
from classes import MarcToDc


def main():
	options = docopt(__doc__)
	
	if options['--file']:
		with open(options['<path>'], 'r') as file:
			marcxml = file.read()
	elif options['-']:
		marcxml = sys.stdin.read()
	else:
		sys.exit()

	sys.stdout.write(str(MarcToDc(marcxml)))
	sys.exit()


if __name__ == "__main__":
    main()
