#!/usr/bin/env python
"""Convert MARCXML to Facebook Open Graph"""

import sys
from classes import MarcXmlToOpenGraph

if __name__ == "__main__":
    sys.stdout.write(str(MarcXmlToOpenGraph(sys.stdin.read())))
